[package]
name = "rfinancial"
version = "1.3.0"
edition = "2024"
include = ["src/**/*", "Cargo.toml", "README.md"]
homepage = "https://github.com/seanzian2093/rust-numpy-financial"
description = "A financial crate mimicking `numpy_financial` in Python"
repository = "https://github.com/seanzian2093/rust-numpy-financial"
keywords = ["finance", "mathematics", "investment", "algorithms", "development-tools"]
categories = ["finance", "mathematics"]
license = "MIT"
rust-version = "1.98.1"
authors = ["Sean Zian"]

[badges]
maintenance = { status = "actively-developed"}

[dependencies]
log = "0.4.34"
thiserror = "2.0.21"
